### ISSUE TITLE
Color of thumb circle not equals underlying color

### ISSUE THREAD

**Issue by S-Man42** [itome/flutter_circle_color_picker#4]
![colorpicker](https://user-images.githubusercontent.com/16626063/78888393-d0b28c00-7a61-11ea-8744-2ad8cb1175aa.png)
![colorpicker2](https://user-images.githubusercontent.com/16626063/78888502-08213880-7a62-11ea-8849-cf1b84deeca5.png)

As you can see at these screenshots, and even in your demo videos, in the range of light green and red, the thumb has not the same color as the underlying color of the circle (it is turqoise and pink instead). Maybe there's a slight shift of the hue values?

**Comment by mavanpee** [comment]
I resolved this on my own download.  It's because the underlying gradient isn't drawn correctly, as you can see the red section is much larger than the blue, but they should be equal in length.  It's a lot more noticeable if you increase the stroke width to something like 20+.

Luckily it's fixed with one line change!

In the _CirclePickerPainter, the one responsible for drawing the circle, change the createShader lines as follows (commented our old line in favour of the new one).  Note that to avoid conflicts, I had to rename the "center" variable to be called "circleCenter" instead.  Here's the change:

```
        final sweepShader = sweepGradient.createShader(
            // Rect.fromLTWH(0, 0, radio, radio),                  // --> OLD line
            Rect.fromCircle(center: circleCenter, radius: radio),  // New Line; changed "centre" to "circleCenter"
        );
```

**Comment by itome** [comment]
@mavanpee Thank you! Would you make PR to fix this?

**Comment by mavanpee** [comment]
Hehe.. I'll be completely honest with you, one of the reasons I was being so descriptive in my post is because I have absolutely no idea how to do a PR myself.  I've never really used github before.

**Comment by itome** [comment]
Thanks, I created PR and merged.
https://github.com/itome/flutter_circle_color_picker/pull/10
